### ISSUE TITLE
Containerised Postfix (port 25) crashes SL app and email containers

### ISSUE THREAD

**Issue by LordChunk** [simple-login/app#237] opened 2020-07-09 18:38 UTC
When running Postfix in a containerised environment with port 25 forwarded to its container, causes the SL app and email container to crash on startup with the following error listed below, this seems to be caused by an application (in this case the PostFix container) occupying port 25. I've tried manually setting the postfix port to 25, but that doesn't seem to make a difference.

How to reproduce:
- Setup a standard SL container deployment in K8s
- Run an application on port 25 in the same cluster

Caveats:
The containers only seem to refuse to boot when they are started after a process has claimed the port. If you set the port after the containers are running everything seems to work fine.
```
[2020-07-09 18:23:54 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-07-09 18:23:54 +0000] [1] [INFO] Listening at: http://0.0.0.0:7777 (1)
[2020-07-09 18:23:54 +0000] [1] [INFO] Using worker: sync
[2020-07-09 18:23:54 +0000] [9] [INFO] Booting worker with pid: 9
[2020-07-09 18:23:55 +0000] [10] [INFO] Booting worker with pid: 10
>>> URL: http://[removed domain]
MAX_NB_EMAIL_FREE_PLAN is not set, use 5 as default value
[2020-07-09 18:23:55 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/code/wsgi.py", line 1, in <module>
    from server import create_app
  File "/code/server.py", line 15, in <module>
    from app import paddle_utils
  File "/code/app/paddle_utils.py", line 18, in <module>
    from app.config import PADDLE_PUBLIC_KEY_PATH, PADDLE_VENDOR_ID, PADDLE_AUTH_CODE
  File "/code/app/config.py", line 81, in <module>
    POSTFIX_PORT = int(os.environ["POSTFIX_PORT"])
ValueError: invalid literal for int() with base 10: 'tcp://10.43.72.209:25'
[2020-07-09 18:23:55 +0000] [9] [INFO] Worker exiting (pid: 9)
>>> URL: http://[removed domain]
MAX_NB_EMAIL_FREE_PLAN is not set, use 5 as default value
[2020-07-09 18:23:55 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/code/wsgi.py", line 1, in <module>
    from server import create_app
  File "/code/server.py", line 15, in <module>
    from app import paddle_utils
  File "/code/app/paddle_utils.py", line 18, in <module>
    from app.config import PADDLE_PUBLIC_KEY_PATH, PADDLE_VENDOR_ID, PADDLE_AUTH_CODE
  File "/code/app/config.py", line 81, in <module>
    POSTFIX_PORT = int(os.environ["POSTFIX_PORT"])
ValueError: invalid literal for int() with base 10: 'tcp://10.43.72.209:25'
[2020-07-09 18:23:55 +0000] [10] [INFO] Worker exiting (pid: 10)
[2020-07-09 18:23:55 +0000] [1] [INFO] Shutting down: Master
[2020-07-09 18:23:55 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by LordChunk** [comment] 2020-07-09 23:00
I saw my POSTFIX_SERVER seems to resolve to "tcp://10.43.72.209:25". My simplelogin.env file contains the following variables for postfix: 
```
...
# If you want to use another MTA to send email, you could set the address of your MTA here
# By default, emails are sent using the the same Postfix server that receives emails
POSTFIX_SERVER=postfix.default.svc.cluster.local

POSTFIX_PORT=25
...
```

**Comment by nguyenkims** [comment] 2020-07-13 18:13
@LordChunk From the log, it seems that `POSTFIX_PORT` is set to non-integer number. Do you still have the same error when restarting the server with `POSTFIX_PORT` set to 25 in the config file?

**Comment by arugifa** [comment] 2020-07-15 08:51
I'm also using Simple Login and Postfix inside Docker containers, and don't have any problem so far. So it's definitely not a limitation of SimpleLogin or Docker :wink: 

See https://github.com/arugifa/klougle/blob/f273ec54d289faf0b6cba0ab20431b8eb7ad587d/docker/main.tf#L325,L498

**Comment by nguyenkims** [comment] 2020-07-16 09:25
@arugifa https://github.com/arugifa/klougle seems really cool!

**Comment by LordChunk** [comment] 2020-07-18 16:56
> @LordChunk From the log, it seems that `POSTFIX_PORT` is set to non-integer number. Do you still have the same error when restarting the server with `POSTFIX_PORT` set to 25 in the config file?
Yes I still encounter a similar error when setting the port.
```
>>> URL: http://app.mail.vanooik.com
MAX_NB_EMAIL_FREE_PLAN is not set, use 5 as default value
Traceback (most recent call last):
  File "email_handler.py", line 51, in <module>
    from app import pgp_utils, s3
  File "/code/app/pgp_utils.py", line 7, in <module>
    from app.config import GNUPGHOME
  File "/code/app/config.py", line 81, in <module>
    POSTFIX_PORT = int(os.environ["POSTFIX_PORT"])
ValueError: invalid literal for int() with base 10: 'tcp://10.43.61.228:25'
```

**Comment by LordChunk** [comment] 2020-07-18 16:57
> @LordChunk From the log, it seems that `POSTFIX_PORT` is set to non-integer number. Do you still have the same error when restarting the server with `POSTFIX_PORT` set to 25 in the config file?

Yes, I still encounter a similar error when setting the port.
```
>>> URL: http://[domain]
MAX_NB_EMAIL_FREE_PLAN is not set, use 5 as default value
Traceback (most recent call last):
  File "email_handler.py", line 51, in <module>
    from app import pgp_utils, s3
  File "/code/app/pgp_utils.py", line 7, in <module>
    from app.config import GNUPGHOME
  File "/code/app/config.py", line 81, in <module>
    POSTFIX_PORT = int(os.environ["POSTFIX_PORT"])
ValueError: invalid literal for int() with base 10: 'tcp://10.43.61.228:25'
```

**Comment by nguyenkims** [comment] 2020-07-18 18:23
@LordChunk can you connect to the container via `docker exec -it sl-app python shell.py`  then running this line

```
import os;  print(os.environ["POSTFIX_PORT"])
```

and paste the output here please?

**Comment by LordChunk** [comment] 2020-07-18 22:54
```
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os;  print(os.environ["POSTFIX_PORT"])
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/code/shell.py in <module>
----> 1 import os;  print(os.environ["POSTFIX_PORT"])

/usr/local/lib/python3.7/os.py in __getitem__(self, key)
    679         except KeyError:
    680             # raise KeyError with the original key value
--> 681             raise KeyError(key) from None
    682         return self.decodevalue(value)
    683

KeyError: 'POSTFIX_PORT'
```

**Comment by nguyenkims** [comment] 2020-07-19 20:30
@LordChunk that's indeed a strange issue as this command should print out the Postfix port. Could you paste your config file here after removing all sensitive information like your domains, DB_URI and FLASK_SECRET?

**Comment by LordChunk** [comment] 2020-07-21 11:59
I did some more extensive testing to see what would happen in certain situations as I didn't seem to get the same output each time I ran the command mentioned above.

Case 1: I start the Simplelogin App before I start Postfix
Result: The Simplelogin app runs as intended. When I run ``import os;  print(os.environ["POSTFIX_PORT"])`` it outputs `25`.

Case 2: I start the SL app after I start Postfix.
Result: I get the error as listed in the first post I made. The container crashes so I cannot run ``import os; print(os.environ["POSTFIX_PORT"])``.

Case 3: I start the SL app after I start Postfix with the SL app `entrypoint` set to ``/bin/sh``
Result: When I run ``import os;  print(os.environ["POSTFIX_PORT"])`` I get the following output:
```
root@simplelogin-app-6b8d49cfc9-kb9dr:/code# python shell.py
>>> URL: http://[domain]
MAX_NB_EMAIL_FREE_PLAN is not set, use 5 as default value
Traceback (most recent call last):
  File "shell.py", line 5, in <module>
    from app.config import DB_URI, ALIAS_DOMAINS
  File "/code/app/config.py", line 81, in <module>
    POSTFIX_PORT = int(os.environ["POSTFIX_PORT"])
ValueError: invalid literal for int() with base 10: 'tcp://10.43.175.116:25'
root@simplelogin-app-6b8d49cfc9-kb9dr:/code# import os;  print(os.environ["POSTFIX_PORT"])
bash: syntax error near unexpected token `os.environ["POSTFIX_PORT"]'
root@simplelogin-app-6b8d49cfc9-kb9dr:/code# 
```

All of these cases were tested with the following testfile:
```
# WebApp URL
URL=http://app.[domain]

# domain used to create alias
EMAIL_DOMAIN=[domain]

# transactional email is sent from this email address
SUPPORT_EMAIL=support@[domain]

# custom domain needs to point to these MX servers
EMAIL_SERVERS_WITH_PRIORITY=[(10, "app.[domain].")]

# By default, new aliases must end with ".{random_word}". This is to avoid a person taking all "nice" aliases.
# this option doesn't make sense in self-hosted. Set this variable to disable this option.
DISABLE_ALIAS_SUFFIX=1

# If you want to use another MTA to send email, you could set the address of your MTA here
# By default, emails are sent using the the same Postfix server that receives emails
POSTFIX_SERVER=postfix.default.svc.cluster.local
#POSTFIX_SERVER=10.43.61.228
#POSTFIX_SERVER=192.168.2.147
POSTFIX_PORT=25


# the DKIM private key used to compute DKIM-Signature
DKIM_PRIVATE_KEY_PATH=/dkim.key

# the DKIM public key used to setup custom domain DKIM
DKIM_PUBLIC_KEY_PATH=/dkim.pub.key

GNUPGHOME=/sl/pgp
```

**Comment by nguyenkims** [comment] 2020-07-24 18:55
That's a really strange issue indeed as Postfix and SimpleLogin can be started independently: they only communicate when an email is sent to your server.

If your Postfix is running on the same server, I'd suggest removing the `POSTFIX_SERVER` and `POSTFIX_PORT` option.

**Comment by nguyenkims** [comment] 2020-08-28 10:30
I close this issue, feel free to re-open it if the issue isn't solved :)

**Closed by nguyenkims** 2020-08-28 10:30 UTC
