### ISSUE TITLE
Cannot pass MX record test

### ISSUE THREAD

**Issue by bermudalocket** [simple-login/app#236] opened 2020-07-07 18:07 UTC
Hi, I just recently installed SimpleLogin on my server. I am having trouble with the domain DNS tests provided by SimpleLogin. Specifically the MX record test states it is looking for a target `mysubdomain.mydomain.com` with priority 10. However, on DigitalOcean, it is not possible to remove the period from the end of the target, so the MX record is returned as `mysubdomain.mydomain.com.`. SimpleLogin does not think this is satisfactory and displays an error:

```
Your DNS is not correctly set. The MX record we obtain is:
10 mysubdomain.mydomain.com.
```

**Comment by nguyenkims** [comment] 2020-07-07 22:01
@bermudalocket that's an interesting case indeed. Can you send me (son at simplelogin.io) the domain in question so I can reproduce the issue and fix it?

**Comment by nguyenkims** [comment] 2020-08-28 10:29
@bermudalocket  I close this issue, feel free to re-open it if the issue isn't solved :)

**Closed by nguyenkims** 2020-08-28 10:29 UTC

**Comment by Tsukreya** [comment] 2020-09-18 09:36
Has this been resolved or did the guy just not get back to you? 
If it's the latter, I also am experiencing this, and I can send you the domain and specifics.

**Comment by nguyenkims** [comment] 2020-09-25 17:45
@Tsukreya Don't hesitate to send me the info to son [at] simplelogin.io so I can have a look.

**Comment by GeekAnnoyed** [comment] 2023-09-18 13:41
Hello,
I've just set up my own instance and i'm having the same issue with any custom domain
I have it setup as a subdomain, and I'm trying to register the naked domain

I have also tried a different domain too I get the same error

Something along the line of 
```
 Your DNS is not correctly set. The MX record we obtain is:
10 sl.mydomain.xyz. 
```
I'm using Cloudflare as DNS and I have tried setting the Priority to a random non 10 number and the error updated to reflect that change (I was checking it wasn't just cached)

**Comment by matvanvian** [comment] 2024-07-17 12:00
Run the following command with myuser as postgres username for sl database
`docker exec -it sl-db psql -U myuser simplelogin`

Then do the following:
`UPDATE custom_domain SET verified = true;`

Exit the database shell
`exit`

Your domain should now be verified, and usable as alias domain.
