### ISSUE TITLE
Can't login to paid account

### ISSUE THREAD

**Issue by V8Qxdvixstjg3n7afA** [simple-login/app#227] opened 2020-06-11 17:57 UTC
My password is indicated as incorrect, though I have not changed it recently. I logged in yesterday with no issues and sent several emails using my aliases. I submitted a request to reset the password and have not received any email to do so even though it has been a few hours.

**Comment by nguyenkims** [comment] 2020-06-11 18:07
@V8Qxdvixstjg3n7afA can you please send your account email to hi@simplelogin.io so we can investigate?

**Comment by V8Qxdvixstjg3n7afA** [comment] 2020-06-11 18:36
Thanks very much for the quick reply. Great service so far. Better than Blur in a lot of ways.

**Comment by V8Qxdvixstjg3n7afA** [comment] 2020-06-11 19:09
Sent email.

**Comment by nguyenkims** [comment] 2020-06-15 21:40
@V8Qxdvixstjg3n7afA I guess the issue is fixed now, should I close this issue?

**Closed** 2020-06-16 06:15 UTC
