### ISSUE TITLE
Remove simplelogin email address in the reply

### ISSUE THREAD

**Issue by firyx** [simple-login/app#418] opened 2021-03-26 08:03 UTC
User A (having a regular email e.g. user.a@yahoo.com) sends an email to user B to his SimpleLogin address.

When the user B replies from his protected email (e.g. user.b@gmail.com) to the user A,
the body of the reply contains simplelogin address of the user A, not his real address:

`On Fri, Mar 26, 2021 at 8:49 AM User A - user.a at yahoo.com <xx+xxxxxxxxxxxxxxxxxxxxxxxxxxxxx@simplelogin.co> wrote:`

Can this be changed to:

`On Fri, Mar 26, 2021 at 8:49 AM User A <user.a@yahoo.com> wrote:`

so that we do not have to do it manually if we want to keep replies clean?

Thanks

**Comment by firyx** [comment] 2021-03-26 15:13
What I mean, the reply email from Gmail to SimpleLogin contains:
`On Fri, Mar 26, 2021 at 8:49 AM User A - user.a at yahoo.com <xx+xxxxxxxxxxxxxxxxxxxxxxxxxxxxx@simplelogin.co> wrote:`

SimpleLogin server replaces string `User A - user.a at yahoo.com <xx+xxxxxxxxxxxxxxxxxxxxxxxxxxxxx@simplelogin.co>` in the email body with `User A <user.a@yahoo.com>` in the replay email body

and sends the replay to the User A with the following in the repaly email body:
`On Fri, Mar 26, 2021 at 8:49 AM User A <user.a@yahoo.com> wrote:`

Replacing the string (version with `at` or with `#`) should work for any email provider.

**Comment by nguyenkims** [comment] 2021-03-26 17:57
There's actually this option on the settings page that's hidden at the moment as it doesn't work on Gmail UI. It might make sense to unhide it.

![image](https://user-images.githubusercontent.com/3167780/112673354-e7194980-8e64-11eb-93e8-704aeee7f319.png)

**Comment by firyx** [comment] 2021-03-29 10:01
I'm not sure, but I think this is something different.

I do not want to replace my contact email,
but if User A sends me an email to my SimpleLogin email and I reply e.g. from my Gmail,
he will see in the reply:

```
This is my reply, I'm fine.
    me

On Fri, Mar 26, 2021 at 8:49 AM User A - user.a at yahoo.com <xx+xxxxxxxxxxxxxxxxxxxxxxxxxxxxx@simplelogin.co> wrote:

Hey, how are you?
    User A - sender
```

I think, we can replace his email address, so he will see his own email like:

```
This is my reply, I'm fine.
    me

On Fri, Mar 26, 2021 at 8:49 AM User A <user.a@yahoo.com> wrote:

Hey, how are you?
    User A - sender
```

**Comment by pldavid2** [comment] 2021-05-04 16:53
Hello, I just found out this issue. I understand there is nothing I can do it to fix this as it's a gmail problem, right?

**Comment by developStorm** [comment] 2021-06-06 05:24
> It's a actually a Gmail UI problem. If you use an email client (like Thunderbird), this option works fine.

Any technical detail about this UI problem? I tried looking at the source code of the email and it seems that the address was successfully replaced in the plain text version, while the replacement failed in the quoted-printable version. However the reply address in the quoted-printable is also just the normal quoted-printable encoding and URL encoding (in the <a> tag Gmail added), shouldn't they be easy-replacable as well?

**Comment by nguyenkims** [comment] 2021-06-20 15:49
@developStorm I remember when inspecting the quote part back then, Gmail splits the reverse-alias into several HTML elements that make replacing it difficult. I just retried and it seems that the problem is still there.

**Comment by developStorm** [comment] 2021-06-20 20:56
@nguyenkims It looks to me like it's just a normal full reverse address wrapped in an <a> tag to the reverse addr, without the "splitting" you mentioned? Do you have an example for split version?

![image](https://user-images.githubusercontent.com/59678453/122688027-a7959b80-d1ce-11eb-898f-a266aef29f3b.png)

* BTW even the addr shown above wasn't split, it did not replace by SL when I have the replacement option on which is confuse.

**Comment by nguyenkims** [comment] 2021-06-22 09:44
@developStorm I just tested this scenario with Gmail and the problem is still there

- send a HTML email to an alias, forwarded to a Gmail mailbox
- reply from this mailbox
- the reverse-alias is *not* correctly replaced in the response. I inspect the response and the reverse-alias in the quoted part is split into different HTML elements as you can see in the below screenshot:

![2021-06-22 at 10 35](https://user-images.githubusercontent.com/3167780/122902754-097d0f00-d34f-11eb-9920-51b327402d77.png)

**Comment by developStorm** [comment] 2021-06-22 09:59
@nguyenkims Could you take a look on the email source code (On Gmail, Next to Reply, click More and then Show original). That might omit some auto link conversion / safe redirect features and show what exactly is sent (processed) by SL. The break you are currently seeing could be rendered by Gmail frontend only which is not same as what SL server gets.

**Comment by nguyenkims** [comment] 2021-06-22 10:13
@developStorm this is how this is rendered on Apple Mail so I guess this isn't specific to gmail rendering.

![2021-06-22 at 12 11](https://user-images.githubusercontent.com/3167780/122907118-1ac81a80-d353-11eb-86c3-371cca9897db.png)

**Comment by developStorm** [comment] 2021-06-22 10:25
@nguyenkims Interesting. So there are two situations:
- The situation I posted before where the alias didn't get split (but surrounded by an a tag)
- Part of alias was mistakenly recognized as link and thus broke

In **both** two cases, the alias is not being properly replaced. This is weird because I think for the first case it should at least replace something.

For the second case, we could probably try to replace when HTML tags are ignored. I guess there will be a way to do it, but I'm not certain about the concrete implementation yet.

**Comment by nguyenkims** [comment] 2021-06-22 15:29
@developStorm I'm afraid that other email services can have a similar behavior as Gmail and that's why this reverse-alias replacement option is hidden. I think we can enable this option for users who asked for it or make it under "experimental" features.

**Comment by developStorm** [comment] 2021-06-25 18:27
@nguyenkims Can we use Chrome plugin for replacing instead of doing this on mail backend?

**Comment by nguyenkims** [comment] 2021-06-27 10:01
@developStorm I'm a bit reluctant to allow the extension to modify sensitive info as email content, even if this doesn't require any additional permission.

**Comment by browntownington** [comment] 2021-07-22 10:34
Adding my two cents here :)

My Thunderbird client seems to actually remove or not include the sender email but only the name. Which I'm okay with as the reverse-alias is never exposed.
![image](https://user-images.githubusercontent.com/19516522/126621405-869e0004-b45d-4ddd-b232-75d5436a5193.png)

Using Protonmail I tested both plain-text and html - both provide the full string for the reverse-alias without modifying it with html etc. So a find and replace should work. However the replacement still doesn't work. 

Example 1 - plaintext
![image](https://user-images.githubusercontent.com/19516522/126622040-63d61359-d709-401b-b296-8e0190eac569.png)


Example 2 - html
![image](https://user-images.githubusercontent.com/19516522/126622336-ee800afc-a1c2-4044-8207-f949a61ff1cf.png)
Source
`<div>‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐<br></div><div class="protonmail_quote"><div> On Thursday, July 22nd, 2021 at 7:32 PM, John Wicks &lt;ra+john.at.wicks.com+rzkbm@simplelogin.co&gt; wrote:<br></div><div> <br></div><blockquote type="cite" class="protonmail_quote"><div><p>&nbsp;<br></p></div></blockquote></div><div><br></div>`

**Comment by astaszek** [comment] 2021-12-19 10:05
my problem with protonmail when removing the alias name is that it also removes the end of the domain name in the sender field and also in the original message it kinda doubles the sender address which makes it look weird 

**Example:**

**before replacement**
From: address@my-domain.com
Message : 
...
On Sunday, December 19th, 2021 at 10:52 AM, First_name Last_name - address at my-domain.com <alias> wrote : 

**after replacement**
From: address@my-domain <address@my-domain.com>
Message:
...
On Sunday, December 19th, 2021 at 10:52 AM, First_name Last_name - address at my-domain.com address@my-domain.com wrote :

**Comment by bx2KdaukwF** [comment] 2022-03-10 01:36
I'm having some problems with replacement and ProtonMail too. My experiment:

**a**@company.com - Company X's email (doesn't know about SimpleLogin)
**b**@simplelogin.co - SL alias that will redirect to my maiboxes
**c**@gmail.com - Gmail (my primary normal mailbox at SL) 
**d**@pm.me - ProtonMail (my secondary encrypted maibox at SL)


1. A -> B. Both C and D will receive an email from B.
2. D replies. Here is the problem, A will receive the reply with `<a.at.company.com-noise@simplelogin.co> wrote:`, it doesn't replace anything.

To see why this is not ProtonMail's fault:

3. A replies back. Both C and D will receive a message like `A_reply <b@simplelogin.co> wrote: (B_reply <a.at.company.com-noise@simplelogin.co> wrote: (A_original))`.
4.  C replies. This time everything works perfectly and SL also **solves the past mistakes from the PM bug reply**. The message becomes something like  `C_reply <a@company.com> wrote: (A_reply <b@simplelogin.co> wrote: (B_reply <a@company.com> wrote: (A_original)))`

**Comment by nguyenkims** [comment] 2022-03-13 10:35
@bx2KdaukwF the reverse alias replacement is also handled for base64 email as you can see in this test https://github.com/simple-login/app/blob/350f498b94d5cd4db11ea8a24087077b8a1eb70b/tests/test_email_utils.py#L435

Can you send the message sent in the #2 step with all sensitive information stripped so we can investigate? You can also send the email content directly to me at son[at]simplelogin.io if you prefer.

**Comment by bx2KdaukwF** [comment] 2022-03-13 23:26
I don't think it's hard to reproduce. The following email was a reply from a protonmail to a reverse-alias of a Tutanota contact that wasn't replaced by SL.

Sent message 2:

```
In-Reply-To: <random--3-2@tutanota.com>
References: <random--3-2@tutanota.com>
X-Pm-Origin: internal
X-Pm-Content-Encryption: end-to-end
Subject: Re: First message
To: c.at.tutanota.com_noise@simplelogin.co
From: DDDDDD <d@protonmail.com>
Date: Sun, 13 Mar 2022 22:54:57 +0000
Mime-Version: 1.0
Content-Type: multipart/mixed;boundary=---------------------dddddddddddddddddddddddddddddddd
Message-Id: <very-random-string=@protonmail.com>
X-Pm-Scheduled-Sent-Original-Time: Sun, 13 Mar 2022 22:54:45 +0000
X-Pm-Recipient-Authentication: c.at.tutanota.com_noise%40simplelogin.co=none
X-Pm-Recipient-Encryption: c.at.tutanota.com_noise%40simplelogin.co=none

-----------------------dddddddddddddddddddddddddddddddd
Content-Type: multipart/related;boundary=---------------------gggggggggggggggggggggggggggggggg

-----------------------gggggggggggggggggggggggggggggggg
Content-Type: text/html;charset=utf-8
Content-Transfer-Encoding: base64

PGRpdiBzdHlsZT0iZm9udC1mYW1pbHk6IGFyaWFsOyBmb250LXNpemU6IDE0cHg7Ij5NZXNzYWdl
IDI8YnI+PC9kaXY+PGRpdiBzdHlsZT0iZm9udC1mYW1pbHk6IGFyaWFsOyBmb250LXNpemU6IDE0
cHg7Ij48YnI+PC9kaXY+CjxkaXYgY2xhc3M9InByb3Rvbm1haWxfc2lnbmF0dXJlX2Jsb2NrIiBz
dHlsZT0iZm9udC1mYW1pbHk6IGFyaWFsOyBmb250LXNpemU6IDE0cHg7Ij4KICAgIDxkaXYgY2xh
c3M9InByb3Rvbm1haWxfc2lnbmF0dXJlX2Jsb2NrLXVzZXIgcHJvdG9ubWFpbF9zaWduYXR1cmVf
YmxvY2stZW1wdHkiPgoKICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICA8ZGl2IGNsYXNz
PSJwcm90b25tYWlsX3NpZ25hdHVyZV9ibG9jay1wcm90b24iPgogICAgICAgIFNlbnQgd2l0aCA8
YSB0YXJnZXQ9Il9ibGFuayIgaHJlZj0iaHR0cHM6Ly9wcm90b25tYWlsLmNvbS8iIHJlbD0ibm9v
cGVuZXIgbm9yZWZlcnJlciI+UHJvdG9uTWFpbDwvYT4gc2VjdXJlIGVtYWlsLgogICAgPC9kaXY+
CjwvZGl2Pgo8ZGl2IHN0eWxlPSJmb250LWZhbWlseTogYXJpYWw7IGZvbnQtc2l6ZTogMTRweDsi
Pjxicj48L2Rpdj48ZGl2IGNsYXNzPSJwcm90b25tYWlsX3F1b3RlIj4KICAgICAgICAtLS0tLS0t
IE9yaWdpbmFsIE1lc3NhZ2UgLS0tLS0tLTxicj4KICAgICAgICBPbiBTdW5kYXksIE1hcmNoIDEz
dGgsIDIwMjIgYXQgNzo1NCBQTSwgICZsdDtjLmF0LnR1dGFub3RhLmNvbV9ub2lzZUBzaW1wbGVs
b2dpbi5jbyZndDsgd3JvdGU6PGJyPjxicj4KICAgICAgICA8YmxvY2txdW90ZSBjbGFzcz0icHJv
dG9ubWFpbF9xdW90ZSIgdHlwZT0iY2l0ZSI+Cgo8ZGl2Pk1lc3NhZ2UgMTxicj48L2Rpdj48ZGl2
Pjxicj48L2Rpdj48ZGl2Pi0tIDxicj48L2Rpdj48ZGl2PiBTZW50IHdpdGggVHV0YW5vdGEsIHRo
ZSBzZWN1cmUgJmFtcDsgYWQtZnJlZSBtYWlsYm94LiA8YnI+PC9kaXY+CgoKICAgICAgICA8L2Js
b2NrcXVvdGU+PGJyPgogICAgPC9kaXY+
-----------------------gggggggggggggggggggggggggggggggg--
-----------------------dddddddddddddddddddddddddddddddd--

```

**Comment by bx2KdaukwF** [comment] 2022-03-13 23:50
If I'm interpreting this right, with Gmail it works because it's more simple:

```
Content-Type: multipart/alternative; boundary="@@@@@"

--@@@@@
Content-Type: text/plain; charset="UTF-8"

Message body <- [completely ignored]

--@@@@@
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

Message body

--@@@@@--
```

While ProtonMail uses the format:

```
Content-Type: multipart/mixed;boundary=@@@@@@@@@@

@@@@@@@@@@
Content-Type: multipart/related;boundary=##########

##########
Content-Type: text/html;charset=utf-8
Content-Transfer-Encoding: base64

Message body

##########--
@@@@@@@@@@--
```

Which means that content inside "nested content-types" are not being processed by the alias replacement code?

**Comment by nguyenkims** [comment] 2022-03-16 18:04
@bx2KdaukwF that's indeed strange as all content types should be handled as you can see in https://github.com/simple-login/app/blob/fa2f83dbf49ae1ac271290f33b0b938b21c35178/app/email_utils.py#L1032

We'll try to debug the issue to see maybe the base64 isn't correctly decoded.

**Comment by bx2KdaukwF** [comment] 2022-03-21 23:22
I think the point is that ProtonMail is using the `"multipart/related"`, which from what I see, you just consider as plain text and ignores the possibility of base64 content there.

https://github.com/simple-login/app/blob/a783b78a7f0a082781755c142e41eab420695eda/app/email_utils.py#L1038-L1049

**Comment by nguyenkims** [comment] 2022-04-20 07:52
We have improved the encoding/decoding part and the issue should be fixed now.

**Closed by nguyenkims** 2022-04-20 07:52 UTC
